server:
  port: 8081

spring:
  application:
    name: flight-service
  datasource:
    url: jdbc:mysql://localhost:3306/flightdb
    username: root
    password: Varshi@2001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
