server:
  port: 8080   

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: flight-search-service
          uri: lb://flight-search-service
          predicates:
            - Path=/flights/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
